# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"E\n\x0bStudentInfo\x12\x12\n\nstudent_id\x18\x01 \x01(\x05\x12\x17\n\x0fsemester_filter\x18\x02 \x01(\x05\x12\t\n\x01k\x18\x03 \x01(\x05\"\x1b\n\x0b\x43oursesInfo\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2@\n\tMLService\x12\x33\n\x15RecommendationService\x12\x0c.StudentInfo\x1a\x0c.CoursesInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STUDENTINFO']._serialized_start=17
  _globals['_STUDENTINFO']._serialized_end=86
  _globals['_COURSESINFO']._serialized_start=88
  _globals['_COURSESINFO']._serialized_end=115
  _globals['_MLSERVICE']._serialized_start=117
  _globals['_MLSERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
